#!/bin/bash

set -e

# Assume the tmux session name is the CWD's name
PROJECT_NAME="$(basename $(pwd))"

echo "$(date): reloading the REPL..."

# This assumes the REPL is started in the first pane
tmux send-keys -t "$PROJECT_NAME:0" ":!clear" Enter
tmux send-keys -t "$PROJECT_NAME:0" ":reload" Enter
if ! [ -z "$1" ]; then
    tmux send-keys -t "$PROJECT_NAME:0" "$1" Enter
fi
