cabal-version:   3.0
name:            json-lesson
version:         0.1.0.0
license:         NONE
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
    ghc-options: -Wall

executable json-lesson
    import:           warnings
    main-is:          Main.hs
    other-modules:    AesonBasics
    build-depends:    base ^>=4.17.2.1
                    , aeson
                    , bytestring
                    , text
                    , utf8-string
                    , raw-strings-qq
    hs-source-dirs:   app
    default-language: Haskell2010
    default-extensions:
        OverloadedStrings
      , DeriveGeneric
      , QuasiQuotes
